version: "3.8"

services:
  #Database Service
  db:
    container_name: sgs_mysql
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sporting_goods_store
      MYSQL_ROOT_PASSWORD: sporting_goods_store
    restart: always
  #phpMyAdmin Service
  phpmyadmin:
    container_name: sgs_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
    restart: always
